name: postgres-hasura
services:
  postgres:
    image: postgres:12
    ports:
      - 5432
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
    resources:
      cpu: 250m
      memory: 0.5Gi
  graphql-engine:
    public: true
    image: hasura/graphql-engine:v1.2.2
    ports:
      - 8080
    environment:
      - HASURA_GRAPHQL_ADMIN_SECRET=hasura
      - HASURA_GRAPHQL_DATABASE_URL=postgres://postgres:password@postgres:5432/postgres
      - HASURA_GRAPHQL_ENABLE_CONSOLE='true'
      - HASURA_GRAPHQL_DEV_MODE='true'
      - HASURA_GRAPHQL_ENABLED_LOG_TYPES='startup, http-log, webhook-log, websocket-log, query-log'
      - 'HASURA_GRAPHQL_JWT_SECRET="{\"type\": \"RS256\", \"jwk_url\": \"http://hasura-backend-plus:3000/auth/jwks\"}"'
    resources:
      cpu: 250m
      memory: 0.5Gi
  hasura-backend-plus:
    public: true
    image: nhost/hasura-backend-plus:latest
    ports:
      - 3000
    environment:
      - AUTO_MIGRATE='true'
      - HASURA_GRAPHQL_ADMIN_SECRET=hasura
      - HASURA_ENDPOINT=http://graphql-engine:8080/v1/graphql
      - JWT_ALGORITHM=RS256
      - S3_ENDPOINT=http://minio:9000
      - S3_BUCKET=hasura-backend-plus
      - S3_ACCESS_KEY_ID=minio
      - S3_SECRET_ACCESS_KEY=minio12345
    resources:
      cpu: 250m
      memory: 1Gi
  minio:
    image: minio/minio
    volumes:
      - /data
    environment:
      - S3_BUCKET=hasura-backend-plus
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio12345
    command: "mkdir -p /export/hasura-backend-plus && /usr/bin/minio server /export"
    resources:
      cpu: 250m
      memory: 0.5Gi